### ISSUE TITLE
Doesn't install on Ubuntu

### ISSUE THREAD

**Issue by NoraCodes** [KSP-CKAN/CKAN-deb#2]
```
dpkg: dependency problems prevent configuration of ckan:
 ckan depends on mono-complete (>= 3.10); however:
  Version of mono-complete on system is 3.2.8+dfsg-4ubuntu4.
```

**Comment by Voidi** [comment]
you need a newer mono version, search for a ppa

**Comment by NoraCodes** [comment]
Unfortunately, there are no PPAs for 15.04 that have a newer version. However, CKAN actually works fine with 3.2.8 - could you change the version?

**Comment by politas** [comment]
CKAN requires Mono version 4. It uses elements that are only available in .Net 4.5, which Mono v4 implements. You'll need to go to Mono Project to update Mono. But really, forget about these .deb files; they haven't been updated and never even reached a full release.
